import { StyleSheet, Platform } from 'react-native';

export const wizardStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 5, 5, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  wizardContainer: {
    backgroundColor: '#0A0A0A',
    width: '100%',
    height: '100%',
    paddingTop: Platform.OS === 'ios' ? 50 : 20,
    justifyContent: 'space-between',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  headerTitle: {
    color: '#F8FAFC',
    fontSize: 20,
    fontWeight: '800',
  },
  headerSubtitle: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 2,
  },
  closeButton: {
    padding: 8,
  },
  progressBarBg: {
    height: 4,
    backgroundColor: '#1E293B',
    width: '100%',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#A3E635',
  },
  stepContentContainer: {
    flex: 1,
    width: '100%',
  },
  stepContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  stepTitle: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 24,
    lineHeight: 26,
  },
  sectionLabel: {
    color: '#94A3B8',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 16,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 12,
  },
  selectAllBtn: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  selectAllBtnText: {
    color: '#A3E635',
    fontSize: 12,
    fontWeight: '700',
  },
  locationRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  locationCard: {
    flex: 1,
    backgroundColor: '#18181B',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#27272A',
  },
  activeLocationCard: {
    borderColor: '#A3E635',
    backgroundColor: 'rgba(163, 230, 53, 0.05)',
  },
  locationCardText: {
    color: '#94A3B8',
    fontSize: 15,
    fontWeight: '700',
  },
  activeLocationCardText: {
    color: '#A3E635',
  },
  equipmentScroll: {
    flex: 1,
  },
  checkboxCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#18181B',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  activeCheckboxCard: {
    borderColor: '#3F3F46',
    backgroundColor: '#27272A',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#475569',
    marginRight: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#A3E635',
    borderColor: '#A3E635',
  },
  checkboxText: {
    color: '#E2E8F0',
    fontSize: 15,
    fontWeight: '600',
  },
  daysSelectorRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  dayCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#18181B',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#27272A',
  },
  activeDayCircle: {
    borderColor: '#A3E635',
    backgroundColor: '#A3E635',
  },
  dayCircleText: {
    color: '#94A3B8',
    fontSize: 16,
    fontWeight: '800',
  },
  activeDayCircleText: {
    color: '#0A0A0A',
  },
  durationRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 24,
  },
  durationChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#18181B',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: '#27272A',
  },
  activeDurationChip: {
    borderColor: '#A3E635',
    backgroundColor: '#A3E635',
  },
  durationText: {
    color: '#94A3B8',
    fontSize: 14,
    fontWeight: '700',
  },
  activeDurationText: {
    color: '#0A0A0A',
  },
  splitScroll: {
    flex: 1,
  },
  splitCard: {
    backgroundColor: '#18181B',
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: '#27272A',
  },
  activeSplitCard: {
    borderColor: '#A3E635',
    backgroundColor: 'rgba(163, 230, 53, 0.03)',
  },
  splitCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  splitText: {
    color: '#E2E8F0',
    fontSize: 15,
    fontWeight: '700',
  },
  activeSplitText: {
    color: '#A3E635',
  },
  injuriesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 24,
  },
  injuryChip: {
    backgroundColor: '#18181B',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: '#27272A',
  },
  activeInjuryChip: {
    borderColor: '#F59E0B',
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
  },
  injuryText: {
    color: '#94A3B8',
    fontSize: 14,
    fontWeight: '700',
  },
  activeInjuryText: {
    color: '#F59E0B',
  },
  textAreaContainer: {
    backgroundColor: '#18181B',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#27272A',
    padding: 12,
  },
  textArea: {
    color: '#F8FAFC',
    fontSize: 15,
    textAlignVertical: 'top',
    height: 100,
    fontWeight: '500',
  },
  goalsContainer: {
    gap: 12,
  },
  goalCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#18181B',
    borderRadius: 14,
    padding: 20,
    borderWidth: 1.5,
    borderColor: '#27272A',
  },
  activeGoalCard: {
    borderColor: '#A3E635',
    backgroundColor: 'rgba(163, 230, 53, 0.03)',
  },
  goalInfo: {
    flex: 1,
    marginRight: 16,
  },
  goalLabel: {
    color: '#F8FAFC',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  activeGoalLabel: {
    color: '#A3E635',
  },
  goalDesc: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '600',
  },
  goalIndicator: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#475569',
    justifyContent: 'center',
    alignItems: 'center',
  },
  activeGoalIndicator: {
    borderColor: '#A3E635',
  },
  goalIndicatorInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#A3E635',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 24,
    borderTopWidth: 1,
    borderColor: '#1E293B',
    backgroundColor: '#0A0A0A',
  },
  wizardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
  },
  backBtn: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: '#334155',
  },
  backBtnText: {
    color: '#F8FAFC',
    fontSize: 14,
    fontWeight: '800',
  },
  nextBtn: {
    backgroundColor: '#A3E635',
  },
  nextBtnText: {
    color: '#0A0A0A',
    fontSize: 14,
    fontWeight: '800',
  },
  generateBtn: {
    backgroundColor: '#A3E635',
    shadowColor: '#A3E635',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  generateBtnText: {
    color: '#0A0A0A',
    fontSize: 14,
    fontWeight: '800',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  loadingTitle: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  loadingSubtitle: {
    color: '#94A3B8',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 20,
  },
  reviewContainer: {
    backgroundColor: '#0A0A0A',
    width: '100%',
    height: '100%',
    paddingTop: Platform.OS === 'ios' ? 50 : 20,
    justifyContent: 'space-between',
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderColor: '#1E293B',
  },
  reviewTitle: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '800',
    marginLeft: 12,
  },
  reviewScroll: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  programMetaCard: {
    backgroundColor: '#18181B',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#27272A',
    marginBottom: 20,
  },
  programName: {
    color: '#A3E635',
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 8,
  },
  programDescription: {
    color: '#E2E8F0',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '500',
    marginBottom: 16,
  },
  metaBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaBadge: {
    backgroundColor: '#27272A',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
  },
  metaBadgeText: {
    color: '#F8FAFC',
    fontSize: 12,
    fontWeight: '700',
  },
  reviewWorkoutsLabel: {
    color: '#94A3B8',
    fontSize: 14,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  reviewWorkoutCard: {
    backgroundColor: '#18181B',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  reviewWorkoutHeader: {
    borderBottomWidth: 1,
    borderBottomColor: '#27272A',
    paddingBottom: 10,
    marginBottom: 12,
  },
  reviewWorkoutName: {
    color: '#F8FAFC',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  reviewWorkoutFocus: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '600',
  },
  reviewExercisesList: {
    gap: 12,
  },
  reviewExerciseItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.04)',
  },
  exerciseHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  reviewExerciseName: {
    color: '#E2E8F0',
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
    marginRight: 10,
  },
  matchStatusBadge: {
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 4,
  },
  matchedLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  matchedLabelText: {
    color: '#A3E635',
    fontSize: 10,
    fontWeight: '800',
  },
  reviewExerciseSubtext: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
  },
  reviewExerciseNotes: {
    color: '#64748B',
    fontSize: 11,
    fontStyle: 'italic',
    lineHeight: 16,
    fontWeight: '500',
  },
  reviewActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 24,
    borderTopWidth: 1,
    borderColor: '#1E293B',
    backgroundColor: '#0A0A0A',
    gap: 12,
  },
  // Extra styles for Workout Step 2 folder selector and custom input
  textInput: {
    backgroundColor: '#18181B',
    borderWidth: 1.5,
    borderColor: '#27272A',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: '#F8FAFC',
    fontSize: 15,
    marginBottom: 16,
  },
  folderChipsScroll: {
    marginBottom: 16,
  },
  folderChipsContainer: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 4,
  },
  folderChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#18181B',
    borderWidth: 1.5,
    borderColor: '#27272A',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
  },
  folderChipActive: {
    borderColor: '#A3E635',
    backgroundColor: 'rgba(163, 230, 53, 0.08)',
  },
  folderChipText: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
  },
  folderChipTextActive: {
    color: '#A3E635',
    fontWeight: '700',
  },
});
